version: '3.8'
services:
  user-management:
    build: ./user-management
    ports:
      - "3000:3000"
    depends_on:
      - postgresql
    environment:
      - DATABASE_URL=postgres://user:password@postgresql:5432/userdb
    deploy:
      replicas: 5

  order-management:
    build: ./order-management
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/orderdb
    deploy:
      replicas: 5

  authentication-service:
    build: ./authentication-service
    ports:
      - "3002:3002"
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongodb:27017/authdb
    deploy:
      replicas: 5

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  mongodb:
    image: mongo:latest

  redis:
    image: redis:latest

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
