apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      containers:
      - name: authentication-service
        image: authentication-service:latest
        ports:
        - containerPort: 3002
        env:
        - name: REDIS_URL
          value: "redis://redis:6379"
        - name: MONGO_URL
          value: "mongodb://mongodb:27017/authdb"
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  type: LoadBalancer
  ports:
  - port: 3002
    targetPort: 3002
  selector:
    app: authentication-service
