apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-management
  template:
    metadata:
      labels:
        app: order-management
    spec:
      containers:
      - name: order-management
        image: order-management:latest
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URL
          value: "mongodb://mongodb:27017/orderdb"
---
apiVersion: v1
kind: Service
metadata:
  name: order-management
spec:
  type: LoadBalancer
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app: order-management
